services:
  
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      dev_network:
        ipv4_address: 10.20.0.2
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test

  registry:
    image: registry:2
    hostname: registry
    ports:
      - "5000:5000"
    networks:
      dev_network:
        ipv4_address: 10.20.0.3
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - ./data/registry:/var/lib/registry

  minio:
    image: minio/minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      dev_network:
        ipv4_address: 10.20.0.4
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data

networks:
  dev_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/16
